databases:
  - name: moviereviewsdb
    plan: free
    databaseName: moviereviews
    user: moviereviews

services:
  - type: web
    plan: free
    name: moviereviews
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py runserver"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moviereviewsdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
